apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: fdammacco/kcc-backend:0.2
        # ports:
        #   - containerPort: 8080
        volumeMounts:
          - name: config-volume
            mountPath: /etc/cfg
      volumes:
      - name: config-volume
        configMap:
          name: backend-configmap
          items:
          - key: config.js
            path: config.js      