apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: testprod
spec:
  replicas: 2
  selector:
    matchExpressions:
      - {key: env, operator: In, values: [test, prod]}
  template:
    metadata:
      name: test
      labels:
        env: test
    spec:
      containers:
      - name: nginx
        image: nginx:1.13-alpine
