apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kcc-ingress
spec:
  rules:
    - host: kcc.local
      http:
        paths:
          - backend:
              serviceName: frontend-service
              servicePort: 80  