apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  config.js: |
    var config = {
      port: 8080
    };

    module.exports = config;

# or run command
# kubectl create configmap backend-configmap --from-file=configmaps/config.js