apiVersion: v1
kind: ReplicationController
metadata:
  name: test
spec:
  replicas: 2
  selector:
    env: test
  template:
    metadata:
      name: test
      labels:
        env: test
    spec:
      containers:
      - name: nginx
        image: nginx:1.13-alpine