apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: fdammacco/kcc-frontend:0.2
        # ports:
        #   - containerPort: 8080
        env:
        - name: BACKEND_HOST
          value: backend-service
        - name: USERNAME
          valueFrom:
            secretKeyRef: 
              name: credentials-secret
              key: username
        - name: PASSWORD
          valueFrom: 
            secretKeyRef:
              name: credentials-secret
              key: password